name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        dotnet-version: ['5.0.x', '6.0.x']
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{matrix.dotnet-version}}
    - name: Restore dependencies
      run: dotnet restore Xkit.sln
    - name: Build
      run: dotnet build Xkit.sln --no-restore
    - name: Test
      run: dotnet test Corekit.Tests --no-build --verbosity normal
